application: rat-cat
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /images/favicon\.ico
  static_files: static/images/favicon.ico
  upload: /images/favicon\.ico

- url: /game
  script: main.app

- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /sounds
  static_dir: sounds
- url: /userimages
  static_dir: userimages
- url: /scripts
  static_dir: scripts
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: latest
- name: markupsafe
  version: latest